# Generated by Django 4.1.4 on 2023-01-06 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='finish_at',
        ),
        migrations.AddField(
            model_name='todomodel',
            name='finish_by_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='finish_by_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
